// Code generated by protoc-gen-go.
// source: leveldb_model.proto
// DO NOT EDIT!

package main

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type KeySingular struct {
	Fingerprint      *string `protobuf:"bytes,1,opt,name=fingerprint" json:"fingerprint,omitempty"`
	Timestamp        []byte  `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *KeySingular) Reset()         { *this = KeySingular{} }
func (this *KeySingular) String() string { return proto.CompactTextString(this) }
func (*KeySingular) ProtoMessage()       {}

func (this *KeySingular) GetFingerprint() string {
	if this != nil && this.Fingerprint != nil {
		return *this.Fingerprint
	}
	return ""
}

func (this *KeySingular) GetTimestamp() []byte {
	if this != nil {
		return this.Timestamp
	}
	return nil
}

type ValueSingular struct {
	Value            *float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ValueSingular) Reset()         { *this = ValueSingular{} }
func (this *ValueSingular) String() string { return proto.CompactTextString(this) }
func (*ValueSingular) ProtoMessage()       {}

func (this *ValueSingular) GetValue() float32 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type KeyPlural struct {
	Fingerprint      *string `protobuf:"bytes,1,opt,name=fingerprint" json:"fingerprint,omitempty"`
	OpenTimestamp    []byte  `protobuf:"bytes,2,opt,name=open_timestamp" json:"open_timestamp,omitempty"`
	LastTimestamp    *int64  `protobuf:"varint,3,opt,name=last_timestamp" json:"last_timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *KeyPlural) Reset()         { *this = KeyPlural{} }
func (this *KeyPlural) String() string { return proto.CompactTextString(this) }
func (*KeyPlural) ProtoMessage()       {}

func (this *KeyPlural) GetFingerprint() string {
	if this != nil && this.Fingerprint != nil {
		return *this.Fingerprint
	}
	return ""
}

func (this *KeyPlural) GetOpenTimestamp() []byte {
	if this != nil {
		return this.OpenTimestamp
	}
	return nil
}

func (this *KeyPlural) GetLastTimestamp() int64 {
	if this != nil && this.LastTimestamp != nil {
		return *this.LastTimestamp
	}
	return 0
}

type ValuePlural struct {
	Value            []*ValuePlural_Value `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *ValuePlural) Reset()         { *this = ValuePlural{} }
func (this *ValuePlural) String() string { return proto.CompactTextString(this) }
func (*ValuePlural) ProtoMessage()       {}

func (this *ValuePlural) GetValue() []*ValuePlural_Value {
	if this != nil {
		return this.Value
	}
	return nil
}

type ValuePlural_Value struct {
	Timestamp        *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value            *float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ValuePlural_Value) Reset()         { *this = ValuePlural_Value{} }
func (this *ValuePlural_Value) String() string { return proto.CompactTextString(this) }
func (*ValuePlural_Value) ProtoMessage()       {}

func (this *ValuePlural_Value) GetTimestamp() int64 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *ValuePlural_Value) GetValue() float32 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

func init() {
}
